export const theme = {
  colors: {
    background: '#f4f6fa',
    backgroundElevated: '#ffffff',
    surfaceMuted: '#eef1f7',
    textPrimary: '#0c1222',
    textSecondary: '#5c6578',
    textMuted: '#8b95a8',
    primary: '#1e3a5f',
    primaryMid: '#2d5a8c',
    primaryLight: '#e8eef6',
    accent: '#c9a227',
    accentMuted: '#f5edd8',
    success: '#0d9488',
    successMuted: '#ccfbf1',
    danger: '#dc2626',
    dangerMuted: '#fee2e2',
    border: '#e2e6ef',
    borderSubtle: '#eef1f6',
    overlay: 'rgba(12,18,34,0.45)',
    rating: '#f59e0b',
    bestDeal: '#0f766e',
    coupon: '#7c3aed',
    ripple: '#1e3a5f',
  },
  radius: {
    sm: 10,
    md: 14,
    lg: 20,
    xl: 28,
    full: 9999,
  },
  spacing: {
    xs: 6,
    sm: 10,
    md: 14,
    lg: 18,
    xl: 24,
    xxl: 32,
  },
  shadow: {
    card: {
      shadowColor: '#0c1222',
      shadowOpacity: 0.07,
      shadowRadius: 20,
      shadowOffset: { width: 0, height: 8 },
      elevation: 4,
    },
    soft: {
      shadowColor: '#0c1222',
      shadowOpacity: 0.05,
      shadowRadius: 12,
      shadowOffset: { width: 0, height: 4 },
      elevation: 2,
    },
  },
  typography: {
    hero: { fontSize: 26, fontWeight: '800' as const, letterSpacing: -0.5 },
    title: { fontSize: 20, fontWeight: '700' as const, letterSpacing: -0.3 },
    subtitle: { fontSize: 15, fontWeight: '600' as const },
    body: { fontSize: 15, fontWeight: '500' as const },
    caption: { fontSize: 13, fontWeight: '500' as const },
    micro: { fontSize: 12, fontWeight: '600' as const },
  },
};
